# Generated by Django 5.0.3 on 2024-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='apellido',
            new_name='cuit',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='razon_social',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.CharField(max_length=45),
        ),
    ]
