# Generated by Django 5.0.3 on 2024-03-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_rename_apellido_proveedor_cuit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='dni',
            new_name='celular',
        ),
    ]
